### ISSUE TITLE
Context Global_Scope not supported/working

### ISSUE THREAD

**Issue by moehajj** [verygoodsecurity/starlarky#84]
## Problem or feature statement
Assigning script context bindings/attributes to global scope are currently not seen by the `LarkyScriptEngine`.

## Testing scenarios
I added the following test to `starlarky/larky/src/test/java/com/verygood/security/larky/jsr223/LarkyScriptEngineTest.java`
```java
  @Test
  public void testEngine_globalContext_ok() throws Exception {
    // Expect
    String exp_result = "Hello from Global Scope\n";

    // Setup
    String ctxScript =
            "def process(msg):\n" +
                    "    print(msg)\n" +
                    "process(my_msg)";


    String larky_msg = "Hello from Global Scope";

    SimpleScriptContext context = new SimpleScriptContext();
    context.setAttribute("my_msg", larky_msg, ScriptContext.GLOBAL_SCOPE);
    StringWriter sw = new StringWriter();
    context.setWriter(new PrintWriter(sw));

    // Execute
    instance.setContext(context);
    LarkyCompiledScript compiled = (LarkyCompiledScript) ((LarkyScriptEngine) instance).compile(ctxScript);
    compiled.eval();

    // Assert
    assertEquals(exp_result, sw.toString());
  }
```

## Error Output
```shell
testEngine_globalContext_ok(com.verygood.security.larky.jsr223.LarkyScriptEngineTest)  Time elapsed: 0.012 sec  <<< ERROR!
javax.script.ScriptException: Error compiling Starlark program: larky.star
larky.star:3:9: name 'my_msg' is not defined
	at com.verygood.security.larky.jsr223.LarkyCompiledScript.eval(LarkyCompiledScript.java:59)
	at javax.script.CompiledScript.eval(CompiledScript.java:106)
	at com.verygood.security.larky.jsr223.LarkyScriptEngineTest.testEngine_globalContext_ok(LarkyScriptEngineTest.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: Error compiling Starlark program: larky.star
larky.star:3:9: name 'my_msg' is not defined
	at com.verygood.security.larky.parser.LarkyEvaluator.compileStarlarkProgram(LarkyEvaluator.java:245)
	at com.verygood.security.larky.parser.LarkyEvaluator.eval(LarkyEvaluator.java:83)
	at com.verygood.security.larky.parser.LarkyScript.loadStarFileInternal(LarkyScript.java:179)
	at com.verygood.security.larky.parser.LarkyScript.getStarFileWithTransitiveImports(LarkyScript.java:164)
	at com.verygood.security.larky.parser.LarkyScript.evaluate(LarkyScript.java:140)
	at com.verygood.security.larky.parser.DefaultLarkyInterpreter.evaluate(DefaultLarkyInterpreter.java:37)
	at com.verygood.security.larky.parser.DefaultLarkyInterpreter.evaluate(DefaultLarkyInterpreter.java:33)
	at com.verygood.security.larky.jsr223.LarkyCompiledScript.eval(LarkyCompiledScript.java:55)
	... 36 more
```

## Steps to Reproduce
```shell
$ cd larky && mvn clean test
```

**Comment by mahmoudimus** [comment]
@moehajj - this is by design. why do you need a global context?
